config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts, except: :index
  resources :users, only: :show
  #resources :categories
  resources :posts do
    post :confirm,action: :confirm_new, on: :new
    #resources :likes, only: [:create, :destroy]
    resources :answers
  end
  #require 'bootsnap/setup'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_category
  has_many :posts, through: :post_categories
end

app/models/like.rb
class Like < ApplicationRecord
  validates_uniqueness_of :post_id, scope: :user_id
  belongs_to :post, counter_cache: :likes_count
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  validates :title, :content, :image, presence: true
  belongs_to :user
  has_many :post_category
  has_many :categories, through: :post_category
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
end

app/models/post_category.rb
class PostCategory < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  def already_liked?(question)
    self.likes.exists?(question_id: questions.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def create
    Category.create(category_params)
    if @category.save
      redirect_to root_path, notice: '登録しました'
    else
      render :new
    end
  end


private
  def category_params
    params.require(:post).permit(:post_ids[])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @like = current_user.likes.create(post_id: params[:post_id])
        redirect_back(fallback_location: root_path)
    end

    def destroy
        @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        @like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.includes(:user)
    @posts = Post.includes(:user).order("created_at DESC").page(params[:page]).per(5)
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])
    @like = Like.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :image).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>


<!-- ページネーション -->

<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Microposts</title>
    <%= csrf_meta_tags %>

    <!-- コード追加 Bootstrap CSS読み込みコード-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- コード追加 Bootstrap JavaScript読み込みコード-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>



  <head>
    <title>Staff-Board</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   <!-- <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700|Noto+Sans+JP:400,700" rel="stylesheet"> -->
    
  </head>
  <body>
    <header class="header">
      <div class="header__title">
        <%= link_to "Staff-Board", root_path, class: "header__title--text" %>
      </div>
      <div class="header__right">
        <% if user_signed_in? %>
          <%= link_to current_user.nickname, user_path(current_user), class: "header__right--btn" %>
          <%= link_to "新規投稿", new_post_path, class: "header__right--btn" %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header__right--btn" %>
        <% else %>
          <%= link_to "ログイン", new_user_session_path, class: "header__right--btn" %>
          <%= link_to "新規登録", new_user_registration_path, class: "header__right--btn" %>
        <% end %>
      </div>
    </header>
    <div class="navi">
      <ul class="navi__low">
        <a href="" class="btn btn04">category</a>
        <a href="" class="btn btn04">bland</a>
        <a href="" class="btn btn04">men</a>
        <a href="" class="btn btn04">women</a>
        <a href="" class="btn btn04">favorite</a>
        <a href="" class="btn btn04">ranking</a>
      </ul>
    </div>
    <div class="contents">
  <%= yield %>
    <footer>
    <div class="social">
      <div class="social__left">
      <a href="https://twitter.com/">
        <p><i class="fab fa-twitter"></i></p>
      </a>
      </div>
      <div class="social__senter">
      <a href="https://www.facebook.com/">
      <p><i class="fab fa-facebook-f"></i></p>
      </div>
      <div class="social__right">
      <a href="https://www.instagram.com/">
      <p><i class="fab fa-instagram"></i></p>
      </div>
    </footer>
  </body>
</html>

app/views/posts/_posts.html.erb
<td><%= post.title %></td>

app/views/posts/edit.html.erb
<div class="content__title">
  投稿の編集
</div>
<%= form_with model: @post, class: :form, local: true do |form| %>
  <%= form.text_field :title, placeholder: :タイトル, class: :form__title %>
  <%= form.text_area :content, placeholder: :ブログ本文, class: :form__text %>
  <%= form.file_field :image %> 
  <%= form.submit '投稿する', class: :form__btn %>
<% end %>

app/views/posts/index.html.erb
<div class="contents">
  <div class="contents__top">
    <%= image_tag 'sample.jpg', class: "sample-image" %>
</div>
<% @posts.each do |post| %>
  <div class="content">
    <div class="content__left">
      <div class="content__left--image">
        <%= image_tag post.image.url if post.image.present? %>
      </div>
    </div>  
    <div class="content__right">
      <div class="content__right__top">
        <%= link_to post.title, post_path(post.id), class: "content__right__top--title" %>
      </div>
      <div class="content__right__bottom">
        <div class="content__right__bottom--userName">
          <%= link_to post.user.nickname, user_path(post.user), class: "content__right__bottom--userName--btn" %>
        </div>
        <div class="content__right__bottom--date">
          <%= post.created_at.strftime("%Y.%m.%d") %>
        </div>
      </div>
    </div>
   </div> 
<% end %>
<%= paginate(@posts) %>

app/views/posts/new.html.erb
<div class="content__title">
  新規記事の作成
</div>
<%= form_with model: @post, class: :form, local: true do |form| %>
  <%= form.text_field :title, placeholder: :タイトル, class: :form__title %>
  <%= form.text_area :content, placeholder: :ブログ本文, class: :form__text %>
  <%= form.file_field :image,  class: :form__image %> 
  <%= form.submit '投稿する', class: :form__btn %>
<% end %>

app/views/posts/show.html.erb
<div class="postTitle">
  <%= @post.title %>
</div>
<div class="postDate">
  <%= @post.created_at %>
</div>
<div class="postAuthor">
</div>
<% if user_signed_in? && current_user.id == @post.user_id %>
<div class="postManage">
  <%= link_to "編集", edit_post_path(@post.id), class: "postManage__edit" %>
  <%= link_to "削除", post_path(@post.id), method: :delete, class: "postManage__delete" %>
</div>
<% end %>
<div class="postText">
  <div class="postText__image">
    <%= image_tag @post.image.url, size: '300x200' %>
  </div>
  <div class="postText__sentence">
    <%= simple_format @post.content %>
  </div>
</div>

app/views/users/show.html.erb
<div class="postTitle">
  <%= @user.nickname %>さんの投稿一覧
</div>
<% @posts.each do |post| %>
  <div class="content">
    <div class="content__left">
      <div class="content__left--image">
        <%= image_tag post.image.url if post.image.present? %>
        </div>
    </div>
    <div class="content__right">
      <div class="content__right__top">
        <%= link_to post.title, post_path(post.id), class: "content__right__top--title" %>
      </div>
      <div class="content__right__bottom">
        <div class="content__right__bottom--userName">
          <%= link_to post.user.nickname, user_path(post.user), class: "content__right__bottom--userName--btn" %>
        </div>
        <div class="content__right__bottom--date">
          <%= post.created_at %>
        </div>
      </div>
    </div>
  </div>
<% end %>